# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.55453765 0.66379506 0.79666411 ... 0.70378213 0.12579705 0.8371159 ]
 [0.23614762 0.59848519 0.55816753 ... 0.71024322 0.47948677 0.84937481]
 [0.99495671 0.72091493 0.74219609 ... 0.01401857 0.60319738 0.37707558]
 ...
 [0.732379   0.16896248 0.90261926 ... 0.78783971 0.82206619 0.52149687]
 [0.02313805 0.67779569 0.7174339  ... 0.16637965 0.50637498 0.58419727]
 [0.2616721  0.12941    0.00970286 ... 0.61021557 0.58930016 0.89973593]]
[[0.17372451 0.63671317 0.72019133 ... 0.95423736 0.8985413  0.37776192]
 [0.35216015 0.58020903 0.4595278  ... 0.583788   0.77968236 0.64908606]
 [0.30823313 0.93650763 0.48524772 ... 0.33814611 0.72251517 0.83947711]
 ...
 [0.25323495 0.29217522 0.6959683  ... 0.84917426 0.71358286 0.84014167]
 [0.27947369 0.94683376 0.69973746 ... 0.16996914 0.10521004 0.30271743]
 [0.45319857 0.03623864 0.10721627 ... 0.39021416 0.92375206 0.9579302 ]]


Без использования numpy

In [3]:
def mult(a, b):
    result = None
    m = []
    n = len(a)
    for i in range(n):
        m.append([])
        for j in range(n):
            t = 0
            for k in range(n):
                t += a[i][k] * b[k][j]
            m[-1].append(t)
    return np.asarray(m)

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.matmul(a, b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 484 ms
Wall time: 487 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 4.99 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.531219595563016e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]

In [9]:
def scalar_product(a,b):
    s = sum([j * b[i] for i, j in enumerate(a)])
    return s

In [10]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [11]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 15.6 ms
Wall time: 996 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** реализации функций NumPy написаны на низкоуровневых языках: многие ключевые части написаны на языке программирования C, что позволяет достичь высокой производительности. Язык C обеспечивает низкоуровневый доступ к памяти и эффективное выполнение операций. Некоторые операции в NumPy автоматически распараллеливаются для использования многопроцессорных систем. Массивы NumPy представляют собой блоки памяти, которые могут быть эффективно использованы благодаря локализованному доступу

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [12]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    res = a.diagonal()
    res = res[res % 2 == 0]
    return np.sum(res)

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 4, 6, 5, 3],
       [4, 9, 7, 1, 7],
       [3, 5, 9, 8, 7],
       [9, 3, 9, 7, 3],
       [6, 4, 9, 2, 6]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


14

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [15]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    def f(row):
        i = np.arange(1, row.shape[0] + 1)
        result = row / i
        return result
    
    X = np.asarray(A)
    if X.ndim == 1:
        X = np.asarray([X])
    
    result = np.cumsum(X, axis=1)
    result = np.apply_along_axis(f, axis=1, arr=result)
    return result

In [16]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[5.37004382e-02 9.51456265e-02 6.21675812e-01 7.55824650e-02
 3.82353419e-01 3.26113579e-01 9.28872004e-01 8.14131726e-01
 8.92470661e-01 7.21480364e-01 4.96028235e-01 6.05275907e-01
 4.74815504e-01 2.32685416e-01 7.11577797e-01 9.42807144e-01
 8.33276701e-01 4.51614103e-01 4.64943773e-01 6.04200463e-02
 8.33584670e-01 5.47627816e-01 3.63713001e-01 3.15404136e-01
 4.38603058e-01 9.59379995e-01 6.07056696e-01 8.30901768e-01
 9.67368720e-02 2.07245350e-01 4.84605185e-01 6.10304567e-01
 4.51073353e-01 2.21642082e-01 7.38785022e-02 7.19057337e-01
 5.71511033e-02 5.97786752e-01 2.85284538e-01 9.92658570e-01
 5.58437483e-01 6.63703244e-02 5.80171301e-01 4.99241209e-01
 2.71765058e-01 7.53911430e-01 8.49205364e-01 3.14950669e-01
 9.16386965e-01 9.75682873e-01 9.42243718e-01 1.91519119e-01
 4.86729282e-01 9.54110003e-01 5.85213589e-01 5.01239579e-01
 5.12448417e-01 4.26953624e-01 1.34095213e-01 5.34456516e-01
 5.65623772e-01 6.90267839e-01 1.18365839e-01 5.23946866e-01
 9.53780031e-01 6.400671

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [17]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    i = np.where(a[:-1] != a[1:])[0]
    i = np.concatenate(([0], i + 1, [len(a)]))
    unique_elements = a[i[:-1]]
    counts = np.diff(i)
    return unique_elements, counts

In [18]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
x, num

CPU times: total: 0 ns
Wall time: 998 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2], dtype=int64))

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [19]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    i_odd = np.arange(1, X.size, 2)
    i_even = np.arange(0, X.size, 2)
    f = np.vectorize(lambda x: x**3)
    X_new = X.copy()
    X_new[i_odd] = a
    X_new[i_even] = f(X[i_even])[::-1]
    return np.concatenate([X, X_new])

In [20]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: total: 0 ns
Wall time: 997 µs
